version: '2.1'
services:
  amore:
    build: .
    env_file:
      - postgres_config.env
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    command: ./start.sh
    volumes:
      - amore_log:/usr/app/data

  db:
    image: postgres:latest
    env_file:
      - postgres_config.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - amore_db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: cfkfl1245@gmail.com
      PGADMIN_DEFAULT_PASSWORD: AeIsFrAe1999#amore
      PGADMIN_LISTEN_PORT: 80
      # PGADMIN_CONFIG_DEFAULT_SERVER: "0.0.0.0"
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  amore_db:
  amore_log:
  pgadmin-data: